#springSecurity
spring:
  security:
    user:
      name: user
      password: 123456

  # datasource
  datasource:
    url: jdbc:mysql://localhost:3306/security_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: louiema1n
#    jpa
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: create-drop
# ־
logging:
  level:
#    hibernate
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace